[package]
name = "lines"
version = "0.1.0"
edition = "2021"
description = "Get the total line of a file in a directory from the CLI."

[dependencies]
clap = { version = "3.1.18", features = ["derive"] }
encoding_rs = { version = "0.8.31" }
encoding_rs_io = { version = "0.1.7" }